### ISSUE TITLE
not sure where to put this but... can i join?

### ISSUE THREAD

**Issue by Hyp3rionM4x** [iamsjy17/Plotta.js#28]
Hello. I'm a "Webintegrator" from Denmark. Not sure where to put this and i don't have much overtime. But i stumpled upon this (and some other) projects like this, because i needed it for my math class in schools (long story).

Anywho, i find this project fun, so i was wondering if i could join in on the fun?

You can write me if so... i can pitch in whenever :)

PS:
Not the biggest fan of GitHub because not much familiar with their tools, but still, i'm around if you wish me to join! ^^

**Comment by iamsjy17** [comment]
First of all, sorry for the late reply.

Thank you very much. However, this project is not yet ready for collaboration such as coding rules, pull request rules, CI/CD, testing, etc. We will send you a letter when we are ready to collaborate. Thank you.
