### ISSUE TITLE
Legend values calculating wrong

### ISSUE THREAD

**Issue by kupietools** [iamsjy17/Plotta.js#35]
Take a look at this screenshot of your demo:

![image](https://user-images.githubusercontent.com/26891995/150660704-2b507737-27cb-45e1-be8f-adf27d50a515.png)
 
The cos is drawn in the right place, but the legend gives its value as around -22. This is completely wrong. I'm finding that every time I add more than one line, the first one gives incorrect values in the legend.

**Comment by kupietools** [comment]
I fixed it, might have come up with a pretty kludgy solution but it works. It looks like setting up the legend was changing the underlying table data because you assigned a variable by reference instead of by value.  I filed a pull request.

**Comment by iamsjy17** [comment]
Thanks for reporting.

I uploaded a [pr](https://github.com/iamsjy17/Plotta.js/pull/38) that solves the problem.

Thank you very much. 👍 👍 👍
