### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by ashemetov** [iamsjy17/Plotta.js#7]
Thank you for the nice library.
Is it possible to tag releases? Is that case specific release can be downloaded\used, Right now only latest one is available.

**Comment by iamsjy17** [comment]
Thank you for your feedback.
I will add release tags and CHANGELOG from the next version.

**Comment by iamsjy17** [comment]
@ashemetov  Sorry for being so late. I've added the tags and will be actively updating plotta.js. :D
