### ISSUE TITLE
Title and legend

### ISSUE THREAD

**Issue by ashemetov** [iamsjy17/Plotta.js#9]
Looks like there is no way to hide title and legend. Best for title is set it to ' ', but it still eats some place. And there is an option 'legendVisible', however function name shown at the bottom even if 'legendVisible' set to 'false'.
Config options (like 'visible') for title and legend will be helpful.

**Comment by ashemetov** [comment]
Request for improvement: user can hold right mouse button and move graph. That improvement will be nice addition to ZoomIn\ZoomOut.

**Comment by iamsjy17** [comment]
Thank you for your feedback.
In the next version, I will add the feature you gave me feedback.

**Comment by iamsjy17** [comment]
In response to your comments, the showLegend and showTitle methods have been added(https://github.com/iamsjy17/Plotta.js/pull/40). thank you
